[versions]
jackson= "2.14.2"
jetbrains-annotations = "24.1.0"
swagger-annotations = "2.2.21"
victools="4.38.0"

#Plugin Versions
plugin-defaults = "0.2.0"
plugin-javadoc-links = "0.9.0"
plugin-license = "0.16.1"
plugin-maven-central-publishing = "0.4.1"
plugin-metadata = "0.6.0"


[libraries]
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger-annotations" }


[plugins]
mavencentralpublishing = { id = "io.github.sgtsilvio.gradle.maven-central-publishing", version.ref = "plugin-maven-central-publishing" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version.ref = "plugin-defaults" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version.ref = "plugin-metadata" }
javadoclinks = { id = "io.github.sgtsilvio.gradle.javadoc-links", version.ref = "plugin-javadoc-links" }
license = { id = "com.github.hierynomus.license", version.ref = "plugin-license" }
